# Generated by Django 4.0.5 on 2022-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0003_answer_question_delete_questions_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
