# Generated by Django 4.0.5 on 2022-06-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0005_alter_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='photo',
        ),
    ]
